version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    networks:
      - no-internet
    restart: always
  nginx:
    image: nginx:1.20.2
    container_name: nginx-proxy
    ports:
      - "8989:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - no-internet
      - internet
    restart: always

networks:
  internet: {}
  no-internet:
    internal: true
